"""Generate per-project DATA figures (bifurcation diagram + data statistics/coverage).
Outputs land in each project's own data_gen/ folder as .png and .pdf.
Run from paper/ :  python _make_data_figs.py
"""
import torch, numpy as np, os
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
from collections import Counter
os.chdir(os.path.dirname(os.path.abspath(__file__)))

def save(fig, proj, name):
    d=f'{proj}/data_gen'; os.makedirs(d, exist_ok=True)
    fig.savefig(f'{d}/{name}.png', dpi=200, bbox_inches='tight')
    fig.savefig(f'{d}/{name}.pdf', bbox_inches='tight')
    plt.close(fig); print('wrote', f'{d}/{name}.(png|pdf)')

# ---------------- 1D_p ----------------
d=torch.load('1D_p/data/p_solutions_lookup.pt',map_location='cpu',weights_only=False)
pv=d['p_values'].numpy(); sbp=d['solutions_by_p']; bid=d['branch_ids_by_p']
P=[];U0=[];B=[];K=[]
for i in range(len(pv)):
    s=sbp[i]
    if s is None or len(s)==0: continue
    s=s.numpy() if torch.is_tensor(s) else np.asarray(s)
    k=s.shape[0]; K.append(k)
    bi=bid[i] if bid is not None else list(range(k))
    bi=bi.numpy() if torch.is_tensor(bi) else np.asarray(bi)
    for j in range(k):
        P.append(pv[i]); U0.append(float(s[j,0])); B.append(int(bi[j]))
# NOTE: bifurcation diagrams are now generated by _make_bifurcation_figs.py
# (original continuation/fold-curve method in the current paper style).
kc=Counter(K); xs=sorted(kc)
fig,ax=plt.subplots(figsize=(3.2,3.0))
ax.bar([str(x) for x in xs],[kc[x] for x in xs],color='#4a6fa5')
ax.set_xlabel('# solutions $k$'); ax.set_ylabel('# params'); ax.set_title('1D-$p$  multiplicity')
save(fig,'1D_p','fig_1Dp_data_stats')

# ---------------- 2D ----------------
d=torch.load('2D/data/p_solutions_lookup_2d_filtered.pt',map_location='cpu',weights_only=False)
sv=d['p_values'].numpy(); sbp=d['solutions_by_p']; coord=d['coord'].numpy()
cidx=int(np.argmin(((coord-np.array([0.5,0.5]))**2).sum(1)))
S=[];UC=[];BI=[];K=[]
for i in range(len(sv)):
    s=sbp[i]
    if s is None or len(s)==0: continue
    s=s.numpy() if torch.is_tensor(s) else np.asarray(s)
    k=s.shape[0]; K.append(k)
    for j in range(k):
        S.append(sv[i]); UC.append(float(s[j,cidx])); BI.append(j)
# NOTE: 2D bifurcation diagram now generated by _make_bifurcation_figs.py
kc=Counter(K); xs=sorted(kc)
fig,ax=plt.subplots(figsize=(3.2,3.0))
ax.bar([str(x) for x in xs],[kc[x] for x in xs],color='#148f77')
ax.set_xlabel('# solutions $k$'); ax.set_ylabel('# params'); ax.set_title('2D  multiplicity')
save(fig,'2D','fig_2D_data_stats')

# ---------------- a2a4 ----------------
allrec=[]
for split in ['train','val','test']:
    allrec+=torch.load(f'a2a4/data/bvp_region_{split}.pt',map_location='cpu',weights_only=False)
A4=np.array([r['params'][0] for r in allrec]); A2=np.array([r['params'][1] for r in allrec])
K=np.array([len(r['solutions']) for r in allrec])
fig,ax=plt.subplots(figsize=(4.2,3.4))
sc=ax.scatter(A4,A2,c=K,s=6,cmap='viridis',linewidths=0)
plt.colorbar(sc,ax=ax,label='# solutions $k$'); ax.set_xlabel('$a_4$'); ax.set_ylabel('$a_2$')
ax.set_title('a2a4  $(a_4,a_2)$ coverage')
save(fig,'a2a4','fig_a2a4_data_stats')
# NOTE: a2a4 bifurcation (a2,a4 scatter + fold curves) now in _make_bifurcation_figs.py
print('ALL DONE')
